addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "1.0.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.8.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.9.29")
addSbtPlugin("au.com.onegeek"    % "sbt-dotenv"          % "2.1.233")
